### ISSUE TITLE
As a developer, I want to ShortDescription, in order to AddedValue.

### ISSUE THREAD

**Issue by farridkun** [aruppert/quizz.me#117]
### Before

I'm just clone this repo for trying a functionality, and when done clone, i do

- [ npm install ] 
- [ npm run server ]
- [ npm run client (in other terminal)]
- [open browser with http://localhost:3000]
- [try a play with single/multiple and got error]
### After

- [ 
![image](https://user-images.githubusercontent.com/50895949/96837065-09e7a200-1470-11eb-8a39-e67a5fe62831.png)
] 

### I'm using a Windows 10 Pro & npm 6.14.8 & node v.12.19.0

**Comment by aruppert** [comment]
You don't have access to a database... see discription. Try the app on https://quizzme.alexanderruppert.com/ or create a database and server and adjust the backend *see discription*
